/**
 * Generates the script every plugin worker starts with.
 *
 * The bootstrap has three parts, in this order:
 *
 * 1. **Hardening prologue** — removes capabilities the plugin must not
 *    have from the worker global *before any plugin code exists*: direct
 *    network access (`fetch`, `XMLHttpRequest`, `WebSocket`, `EventSource`,
 *    `WebTransport`), `importScripts`, persistent browser storage
 *    (`indexedDB`, `caches`, `navigator.storage`), nested workers,
 *    `BroadcastChannel` (would reach the app window) and notifications.
 *    Properties are deleted along the whole prototype chain and then locked
 *    to `undefined` so plugin code cannot restore them.
 * 2. **Runtime** (`workerRuntime.js`) — the RPC client and the `api`
 *    object.
 * 3. **Start** — runs the runtime. When the plugin holds a
 *    `net:fetch:<host>` grant the runtime installs a `fetch` shim that
 *    routes GET requests through the host (and so through the Rust host
 *    allow-list); native `fetch` is never exposed.
 *
 * The plugin module itself arrives later in the `activate` request and is
 * imported from a blob URL inside the worker.
 */
import runtimeSource from "./workerRuntime.js?raw";
import { DEFAULT_TIMEOUT_MS } from "./protocol";
import { methodTimeouts } from "./api";
import { hasAnyFetchPermission } from "./permissions";

/** Globals removed from every plugin worker. */
export const REMOVED_GLOBALS = [
  "XMLHttpRequest",
  "WebSocket",
  "WebSocketStream",
  "EventSource",
  "WebTransport",
  "importScripts",
  "indexedDB",
  "IDBFactory",
  "caches",
  "CacheStorage",
  "Worker",
  "SharedWorker",
  "BroadcastChannel",
  "Notification",
  "RTCPeerConnection",
  "webkitRTCPeerConnection",
] as const;

/** `navigator` members removed from every plugin worker. */
export const REMOVED_NAVIGATOR_MEMBERS = ["storage", "locks", "serviceWorker", "usb", "hid", "serial", "bluetooth"] as const;

/** Options of {@link buildWorkerBootstrap}. */
export interface BootstrapOptions {
  /** Permissions granted to the plugin (only `net:fetch:*` changes the bootstrap). */
  permissions: readonly string[];
}

/**
 * The hardening prologue as a standalone script operating on `self`.
 * Exported separately so tests can run it against a fake global.
 */
export function buildHardening(permissions: readonly string[]): string {
  const shimFetch = hasAnyFetchPermission(permissions);
  return `(function aetherHarden(scope) {
  "use strict";
  function remove(target, name, lock) {
    let object = target;
    while (object) {
      const descriptor = Object.getOwnPropertyDescriptor(object, name);
      if (descriptor) {
        if (descriptor.configurable) {
          try { delete object[name]; } catch (_) { /* keep going */ }
        } else if (descriptor.writable) {
          try { object[name] = undefined; } catch (_) { /* keep going */ }
        }
      }
      object = Object.getPrototypeOf(object);
    }
    if (lock) {
      try {
        Object.defineProperty(target, name, { value: undefined, writable: false, configurable: false, enumerable: false });
      } catch (_) { /* already locked */ }
    }
  }
  const removed = ${JSON.stringify(REMOVED_GLOBALS)};
  for (const name of removed) remove(scope, name, true);
  // Native fetch never survives; with a net:fetch grant the runtime installs a host-routed shim.
  remove(scope, "fetch", ${shimFetch ? "false" : "true"});
  if (scope.navigator) {
    const navigatorMembers = ${JSON.stringify(REMOVED_NAVIGATOR_MEMBERS)};
    for (const name of navigatorMembers) remove(scope.navigator, name, true);
  }
})(self);
`;
}

/** The full worker script for one plugin. */
export function buildWorkerBootstrap(options: BootstrapOptions): string {
  const config = {
    defaultTimeoutMs: DEFAULT_TIMEOUT_MS,
    methodTimeouts: methodTimeouts(),
    installFetchShim: hasAnyFetchPermission(options.permissions),
  };
  return [
    "// AETHER-OS plugin worker bootstrap — generated by src/lib/plugins/bootstrap.ts.",
    '"use strict";',
    buildHardening(options.permissions),
    runtimeSource,
    `aetherPluginRuntime(self, ${JSON.stringify(config)});`,
    "",
  ].join("\n");
}

/** Raw source of the worker runtime (for tests that evaluate it in isolation). */
export const WORKER_RUNTIME_SOURCE: string = runtimeSource;
